name: Build & Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - run: bun run build:exe

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/luagen.exe
          generate_release_notes: true
